additionalPrometheusRulesMap:
  custom-rules:
    groups:
      - name: node-usage-alerts
        rules:
        
        - alert: NodeDown
          expr: up{job="node-exporter"} == 0
          for: 10s
          labels:
            severity: critical
            namespace: monitoring
          annotations:
            summary: "CRITICAL: Node is down!"

        
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 60
          for: 10s
          labels:
            severity: warning
            namespace: monitoring
          annotations:
            summary: "High CPU usage detected"

        
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
          for: 10s
          labels:
            severity: warning
            namespace: monitoring

        
        - alert: LowDiskSpace
          expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 20
          for: 10s
          labels:
            severity: critical
            namespace: monitoring

      - name: kubernetes-health-alerts
        rules:
      
        - alert: PodFailing
          expr: kube_pod_status_phase{phase=~"Failed|Unknown"} > 0 or rate(kube_pod_container_status_restarts_total[1m]) > 0
          for: 10s
          labels:
            severity: critical
            namespace: monitoring
          annotations:
            description: "Pod {{ $labels.pod }} is failing in {{ $labels.namespace }}"

        
        - alert: PodPendingStuck
          expr: kube_pod_status_phase{phase="Pending"} > 0
          for: 10s
          labels:
            severity: warning
            namespace: monitoring

        
        - alert: DeploymentIncomplete
          expr: kube_deployment_status_replicas_available < kube_deployment_spec_replicas
          for: 10s
          labels:
            severity: warning
            namespace: monitoring
