apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hospital-app-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:

  selector:
    matchLabels:
      monitor: "true"

  
  namespaceSelector:
    any: true

  endpoints:
  - port: metrics 
    path: /api/metrics
    interval: 5s
    honorLabels: true
