---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAqhnT5NdGs0B4gHSRW6Lq+vbGmxxZxK/e5qQrY14jYPSNkaIXZmbIHhyZyKwFd4vTmXYeaO1wPmIiMD+wQuPcwASNcnk6zIp10rVXYi4aO5Wd2ypYHWfLNiPNek4DN+IyoIEm4lvF/BV7IfjAal4nIQ7nBIy1Pw9uKZyyFkHeJi5lvqveJEUFP8J3fVapDFE67CE/Q3qhYCFsm2gNZAZmRJeeejN7qd9m+Atdfa3VYR2OTLHdIVlArxJojuGzNhJGeHTTVXt2Lr797RKVWMtbtwTX9xtLYq1ru8HkI2EY1J3VQcYPblU7aWcZH6A5gZkjOuKSnnJZLWJQb051vscq7jfNOWYu1BsiVPr+APnKtp+kj2aldNeAWo4dogTAY9NnPe8s5k5BEVWIk9S9BYJwydEfR5Lo8cqkdxyyyXfg98wqBM6ceqOCXlLt63+ua4siT9PQdjl2c5eN7onYdfWf2RgKFz2p6CqJXaSg6xy8OPxCJvWBwvdz3T2Ru28BKTIUK4X0rIE81SsdwLk6pqV4wPvWywZwwx9IbTQp+lmAZKoEsqKbb4Y5eFhUOWGXf4xF/dlYcWfREdgBxJygy0E0of/wZMFF+0bwgFzKNDb3A3VeAgubPpzjSoaBoKXixrxA2FYCJytYrcf+NeCoO6IOTo2uihdqYIVFP/F38mn0n5dQSrUMwIgxb85HQO5BcgthqNWppAg==
    admin-user: AgApuLo+/MSExlo7iGVC4mE2v885mtf2DtTb2QW6+qWs60scNuSYsfc9CYbBejAUkB9p8nuDuCJu6QSUlqi2uf1L8u0xC4iEEXWsP56I3Psty0kVYR0b8OpiBUgjey2pIes1rJYjvsuc3V/vg5RjPEzZU7lhDvGhbJ3ye/RSik5UwF38IaERZmS/qL790k9aaTVfDqYP0E0wxa/DYh+gh0mhXSLGKKD3yKVAgNUVLMupffoIM2OD+UKbN9/yULNuMAa086Fw3aqwAvP/smaAf2htVUJojEHf/eOj57vy2jGmu6c5QUfl3bYrJTIwbr8MF25Gq6MxC9es+DCc+8J7NvLBJtIqzjbFu6h14pUpbIuJe3x6I43ms2jSvcgybAjKFRgecKK9Tp9vmgwoOuf3KATIrv7UhEboPza2TBz7DLzNhCocd0TtVWE6B7YPC2UQDi1orvVwD5gYFZ20yNthODfvGEyKoVksA52zUn4uAYlvh4dJvRFdgEAyZJmcxxteU1Y2gXINeTQEZ1CJWLXKMrzL0Opbe6rfyNeD5+MNjpdkg67bGAsDO5YoHqZHtuUWPGczRvF88iJyEjqqWYZoEvxyY8+9ZSz9iESd2zPuudvtOKuV+knedrcSQqkPo00N42VcHk/OiBi3jG8fXxbs89H9/7ffa4VItk8MUkeebYNmtA5Be4EjwL/SfmVMPKuq7InxlfOAAQ==
  template:
    metadata:
      name: monitoring-secrets
      namespace: monitoring
    type: Opaque