apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: hospital-alert-config
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  receivers:
  - name: 'null'
  # تعريف الريسيفر العام برابط وهمي لتعطيله
  - name: 'slack-notifications'
    slackConfigs:
    - apiURL:
        key: webhook-url
        name: slack-webhook-secret
      channel: '#void-channel' 
  # تعريف الريسيفر الخاص بك (الرابط الصحيح)
  - name: 'Slack-Notifications'
    slackConfigs:
    - apiURL:
        key: webhook-url
        name: slack-webhook-secret
      channel: '#alerts'
      sendResolved: true
      text: |-
        • *Alert:* {{ .CommonAnnotations.summary }}
        • *Description:* {{ .CommonAnnotations.description }}
        • *Severity:* `{{ .CommonLabels.severity }}`
  route:
    receiver: 'null'
    groupBy: ['alertname', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 3h
    routes:
    - receiver: 'Slack-Notifications'
      matchers:
      - name: alertname
        value: "HospitalServiceDown|PodFailing|PodPendingStuck|DeploymentIncomplete"
        matchType: =~
